export const APPROVALS_INFO = [
  {
    Label: "Aydınlatma Metni",
    Content:
      '<ul className="font-light px-5"> <li className="list-disc"> Bu kampanya IMC Sigorta & Reasürans Brokerliği AŞ. ‘ye ait 0212 700 17 88 numaralı İLKSAN sigorta destek hattından alınan Kasko ve/veya Trafik Sigortası poliçelerinde geçerlidir. </li> <li className="list-disc"> Kampanyaya katılmak için İlksan mensubu ve/veya yakını olunması gerekmektedir. </li> <li className="list-disc"> Satın alınan her Kasko sigortası için 500 TL değerinde A101 Alişveriş Hediye Kodu , Trafik Sigortası için 150 TL değerinde A101 Alişveriş Hediye Kodu kazanılacaktır. </li> <li className="list-disc"> Alışverişe götüren sigortaya katılabilmek ve A101 Alışveriş Hediye Kodu kazanabilmek için &nbsp; <a href="www.tambenimsigortam.com/ilksankampanya" target="_blank" className="underline" > www.tambenimsigortam.com/ilksankampanya </a> &nbsp; katılımcı bilgilerinin bırakılması ve dijital onayların tamamlanması gerekmektedir. </li> <li className="list-disc"> Kampanyaya katılım sağlayan müşterilere IMC Brokerlik tarafından poliçe tanzim tarihinden 60 gün sonra kampanya kodu maili/SMS’i gönderilecektir. Akabinde hediye kodu 81 ilde bulunan tüm A101 mağazalarında kullanabilecektir. </li> <li className="list-disc"> Hediye kodları ile tüm indirim ve kampanyalardan faydalanabilir. (Aldın Aldın, Haftanın Yıldızları v.b) </li> <li className="list-disc"> Hediye kodları, cep telefonu kontörü, Tütün ve tütün mamulleri, elektronik eşya, bebek maması ve mobilya ürünlerinde kullanılamaz. </li> <li className="list-disc"> Gönderilen kodların 1 yıl geçerlilik süresi vardır. Süre sonunda hediye kodu geçerliliğini kaybedecektir. </li> <li className="list-disc"> Hediye kodları online alışveriş için kullanılamaz. </li> <li className="list-disc"> Kampanya diğer kampanyalarla birleştirilemez. </li> <li className="list-disc"> IMC Sigorta & Reasürans Brokerliği ve İlksan, kampanyayı dilediği zaman durdurma ve/veya kampanya koşullarını değiştirme yetkisine sahiptir. </li> <li className="list-disc"> Kampanyaya ait detaylı bilgiye 0212 700 17 88 no’lu İLKSAN sigorta destek hattından ve{" "} <a href="www.tambenimsigortam.com/ilksankampanya" target="_blank" className="underline" > www.tambenimsigortam.com/ilksankampanya </a>{" "} web adresinden ulaşılabilir. </li> </ul>',
  },
  {
    Label:
      "6698 sayılı Kişisel Verilerin Korunması Kanunu çerçevesinde sağlık sigortası sözleşmesi’nin ifası için özel nitelikli kişisel verilerin işlenmesine onay veriyorum. Söz konusu sağlık sigortasının 18 yaş altı aile fertlerimi kapsayacak şekilde bir aile poliçesi biçiminde düzenlenecek olması durumunda poliçe kapsamındaki aile fertlerime ilişkin tüm verileri kendilerini bilgilendirerek paylaşmış olduğumu, kendilerinin de yukarıdaki kapsamda rızalarının bulunduğu ve bu konuda her türlü sorumluluğunun tarafıma ait olduğunu kabul, beyan ve taahhüt ederim.",
    Content:
      '<ul className="font-light px-5"> <li className="list-disc"> Bu kampanya IMC Sigorta & Reasürans Brokerliği AŞ. ‘ye ait 0212 700 17 88 numaralı İLKSAN sigorta destek hattından alınan Kasko ve/veya Trafik Sigortası poliçelerinde geçerlidir. </li> <li className="list-disc"> Kampanyaya katılmak için İlksan mensubu ve/veya yakını olunması gerekmektedir. </li> <li className="list-disc"> Satın alınan her Kasko sigortası için 500 TL değerinde A101 Alişveriş Hediye Kodu , Trafik Sigortası için 150 TL değerinde A101 Alişveriş Hediye Kodu kazanılacaktır. </li> <li className="list-disc"> Alışverişe götüren sigortaya katılabilmek ve A101 Alışveriş Hediye Kodu kazanabilmek için &nbsp; <a href="www.tambenimsigortam.com/ilksankampanya" target="_blank" className="underline" > www.tambenimsigortam.com/ilksankampanya </a> &nbsp; katılımcı bilgilerinin bırakılması ve dijital onayların tamamlanması gerekmektedir. </li> <li className="list-disc"> Kampanyaya katılım sağlayan müşterilere IMC Brokerlik tarafından poliçe tanzim tarihinden 60 gün sonra kampanya kodu maili/SMS’i gönderilecektir. Akabinde hediye kodu 81 ilde bulunan tüm A101 mağazalarında kullanabilecektir. </li> <li className="list-disc"> Hediye kodları ile tüm indirim ve kampanyalardan faydalanabilir. (Aldın Aldın, Haftanın Yıldızları v.b) </li> <li className="list-disc"> Hediye kodları, cep telefonu kontörü, Tütün ve tütün mamulleri, elektronik eşya, bebek maması ve mobilya ürünlerinde kullanılamaz. </li> <li className="list-disc"> Gönderilen kodların 1 yıl geçerlilik süresi vardır. Süre sonunda hediye kodu geçerliliğini kaybedecektir. </li> <li className="list-disc"> Hediye kodları online alışveriş için kullanılamaz. </li> <li className="list-disc"> Kampanya diğer kampanyalarla birleştirilemez. </li> <li className="list-disc"> IMC Sigorta & Reasürans Brokerliği ve İlksan, kampanyayı dilediği zaman durdurma ve/veya kampanya koşullarını değiştirme yetkisine sahiptir. </li> <li className="list-disc"> Kampanyaya ait detaylı bilgiye 0212 700 17 88 no’lu İLKSAN sigorta destek hattından ve{" "} <a href="www.tambenimsigortam.com/ilksankampanya" target="_blank" className="underline" > www.tambenimsigortam.com/ilksankampanya </a>{" "} web adresinden ulaşılabilir. </li> </ul>',
  },
  {
    Label:
      "6563 sayılı Elektronik Ticaretin Düzenlenmesi Hakkında Kanun ve sair mevzuat çerçevesinde tarafıma ticari elektronik ileti gönderilmesine onay veriyorum.",
    Content:
      '<ul className="font-light px-5"> <li className="list-disc"> Bu kampanya IMC Sigorta & Reasürans Brokerliği AŞ. ‘ye ait 0212 700 17 88 numaralı İLKSAN sigorta destek hattından alınan Kasko ve/veya Trafik Sigortası poliçelerinde geçerlidir. </li> <li className="list-disc"> Kampanyaya katılmak için İlksan mensubu ve/veya yakını olunması gerekmektedir. </li> <li className="list-disc"> Satın alınan her Kasko sigortası için 500 TL değerinde A101 Alişveriş Hediye Kodu , Trafik Sigortası için 150 TL değerinde A101 Alişveriş Hediye Kodu kazanılacaktır. </li> <li className="list-disc"> Alışverişe götüren sigortaya katılabilmek ve A101 Alışveriş Hediye Kodu kazanabilmek için &nbsp; <a href="www.tambenimsigortam.com/ilksankampanya" target="_blank" className="underline" > www.tambenimsigortam.com/ilksankampanya </a> &nbsp; katılımcı bilgilerinin bırakılması ve dijital onayların tamamlanması gerekmektedir. </li> <li className="list-disc"> Kampanyaya katılım sağlayan müşterilere IMC Brokerlik tarafından poliçe tanzim tarihinden 60 gün sonra kampanya kodu maili/SMS’i gönderilecektir. Akabinde hediye kodu 81 ilde bulunan tüm A101 mağazalarında kullanabilecektir. </li> <li className="list-disc"> Hediye kodları ile tüm indirim ve kampanyalardan faydalanabilir. (Aldın Aldın, Haftanın Yıldızları v.b) </li> <li className="list-disc"> Hediye kodları, cep telefonu kontörü, Tütün ve tütün mamulleri, elektronik eşya, bebek maması ve mobilya ürünlerinde kullanılamaz. </li> <li className="list-disc"> Gönderilen kodların 1 yıl geçerlilik süresi vardır. Süre sonunda hediye kodu geçerliliğini kaybedecektir. </li> <li className="list-disc"> Hediye kodları online alışveriş için kullanılamaz. </li> <li className="list-disc"> Kampanya diğer kampanyalarla birleştirilemez. </li> <li className="list-disc"> IMC Sigorta & Reasürans Brokerliği ve İlksan, kampanyayı dilediği zaman durdurma ve/veya kampanya koşullarını değiştirme yetkisine sahiptir. </li> <li className="list-disc"> Kampanyaya ait detaylı bilgiye 0212 700 17 88 no’lu İLKSAN sigorta destek hattından ve{" "} <a href="www.tambenimsigortam.com/ilksankampanya" target="_blank" className="underline" > www.tambenimsigortam.com/ilksankampanya </a>{" "} web adresinden ulaşılabilir. </li> </ul>',
  },
  {
    Label:
      "Aydınlatma Metni’nde belirtilen sağlık verilerimin ( söz konusu sağlık sigortasının 18 yaş altı aile fertlerimi kapsayacak şekilde bir aile poliçesi biçiminde düzenlenecek olması durumunda poliçe kapsamındaki aile fertlerime ait verilerin) sağlık sigortası poliçe kapsamındaki işlemlerin yerine getirilmesi amacıyla ilgili acente/broker ile paylaşılmasını;",
    Content:
      '<ul className="font-light px-5"> <li className="list-disc"> Bu kampanya IMC Sigorta & Reasürans Brokerliği AŞ. ‘ye ait 0212 700 17 88 numaralı İLKSAN sigorta destek hattından alınan Kasko ve/veya Trafik Sigortası poliçelerinde geçerlidir. </li> <li className="list-disc"> Kampanyaya katılmak için İlksan mensubu ve/veya yakını olunması gerekmektedir. </li> <li className="list-disc"> Satın alınan her Kasko sigortası için 500 TL değerinde A101 Alişveriş Hediye Kodu , Trafik Sigortası için 150 TL değerinde A101 Alişveriş Hediye Kodu kazanılacaktır. </li> <li className="list-disc"> Alışverişe götüren sigortaya katılabilmek ve A101 Alışveriş Hediye Kodu kazanabilmek için &nbsp; <a href="www.tambenimsigortam.com/ilksankampanya" target="_blank" className="underline" > www.tambenimsigortam.com/ilksankampanya </a> &nbsp; katılımcı bilgilerinin bırakılması ve dijital onayların tamamlanması gerekmektedir. </li> <li className="list-disc"> Kampanyaya katılım sağlayan müşterilere IMC Brokerlik tarafından poliçe tanzim tarihinden 60 gün sonra kampanya kodu maili/SMS’i gönderilecektir. Akabinde hediye kodu 81 ilde bulunan tüm A101 mağazalarında kullanabilecektir. </li> <li className="list-disc"> Hediye kodları ile tüm indirim ve kampanyalardan faydalanabilir. (Aldın Aldın, Haftanın Yıldızları v.b) </li> <li className="list-disc"> Hediye kodları, cep telefonu kontörü, Tütün ve tütün mamulleri, elektronik eşya, bebek maması ve mobilya ürünlerinde kullanılamaz. </li> <li className="list-disc"> Gönderilen kodların 1 yıl geçerlilik süresi vardır. Süre sonunda hediye kodu geçerliliğini kaybedecektir. </li> <li className="list-disc"> Hediye kodları online alışveriş için kullanılamaz. </li> <li className="list-disc"> Kampanya diğer kampanyalarla birleştirilemez. </li> <li className="list-disc"> IMC Sigorta & Reasürans Brokerliği ve İlksan, kampanyayı dilediği zaman durdurma ve/veya kampanya koşullarını değiştirme yetkisine sahiptir. </li> <li className="list-disc"> Kampanyaya ait detaylı bilgiye 0212 700 17 88 no’lu İLKSAN sigorta destek hattından ve{" "} <a href="www.tambenimsigortam.com/ilksankampanya" target="_blank" className="underline" > www.tambenimsigortam.com/ilksankampanya </a>{" "} web adresinden ulaşılabilir. </li> </ul>',
  },
];
